#!/bin/bash

PATH_INSTALL_SCRIPT_PYTHON="/opt/updateGoogleDNS"

export UPDATE_GOOGLE_DNS_LOGS="/var/log/updateGoogleDNS"
export UPDATE_GOOGLE_DNS_JSON=
export UPDATE_GOOGLE_DNS_PROJECT_ID=
export UPDATE_GOOGLE_DNS_ZONE_NAME=

### Check for dir, if not found create it using the mkdir ##
{ # try
    [ ! -d "$UPDATE_GOOGLE_DNS_LOGS" ] && mkdir -p "${UPDATE_GOOGLE_DNS_LOGS}"
} 

/usr/bin/python3 ${PATH_INSTALL_SCRIPT_PYTHON}/updateGoogleDNS.py
